<?php

/**
 * This is the model base class for the table "enroll_form_hillview".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EnrollFormHillview".
 *
 * Columns in table "enroll_form_hillview" available as properties of the model,
 * followed by relations of table "enroll_form_hillview" available as properties of the model.
 *
 * @property integer $enroll_form_id
 * @property string $student_name
 * @property string $parent_name
 * @property string $address
 * @property string $city
 * @property string $parent_email
 * @property string $parent_phone
 * @property string $food_alergies
 * @property string $additional_comments
 * @property string $grade
 * @property string $class_day
 * @property string $order_id
 *
 * @property EnrollForms $enrollForm
 * @property Orders $order
 */
abstract class BaseEnrollFormHillview extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'enroll_form_hillview';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EnrollFormHillview|EnrollFormHillviews', $n);
	}

	public static function representingColumn() {
		return 'student_name';
	}

	public function rules() {
		return array(
			array('enroll_form_id, student_name, parent_name, parent_phone, grade, class_day, city', 'required'),
			array('enroll_form_id', 'numerical', 'integerOnly'=>true),
			array('student_name, parent_name, address, parent_email, city', 'length', 'max'=>255),
			array('parent_phone', 'length', 'max'=>12),
			array('food_alergies', 'length', 'max'=>45),
			array('grade', 'length', 'max'=>4),
			array('class_day', 'length', 'max'=>9),
			array('order_id', 'length', 'max'=>11),
			array('additional_comments, payment_status', 'safe'),
			array('address, parent_email, food_alergies, additional_comments, order_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('enroll_form_id, student_name, parent_name, address, parent_email, parent_phone, food_alergies, additional_comments, grade, class_day, order_id, city, created, payment_status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'enrollForm' => array(self::BELONGS_TO, 'EnrollForms', 'enroll_form_id'),
			'order' => array(self::BELONGS_TO, 'Orders', 'order_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'enroll_form_id' => null,
			'student_name' => Yii::t('app', 'Student Name'),
			'parent_name' => Yii::t('app', 'Parent Name'),
			'address' => Yii::t('app', 'Address'),
			'parent_email' => Yii::t('app', 'Parent Email'),
			'parent_phone' => Yii::t('app', 'Parent Phone'),
			'food_alergies' => Yii::t('app', 'Food Alergies'),
			'additional_comments' => Yii::t('app', 'Additional Comments'),
			'grade' => Yii::t('app', 'Grade'),
			'class_day' => Yii::t('app', 'Class Day'),
			'order_id' => null,
			'enrollForm' => null,
			'order' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('enroll_form_id', $this->enroll_form_id);
		$criteria->compare('student_name', $this->student_name, true);
		$criteria->compare('parent_name', $this->parent_name, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('parent_email', $this->parent_email, true);
		$criteria->compare('parent_phone', $this->parent_phone, true);
		$criteria->compare('food_alergies', $this->food_alergies, true);
		$criteria->compare('additional_comments', $this->additional_comments, true);
		$criteria->compare('grade', $this->grade, true);
		$criteria->compare('class_day', $this->class_day, true);
		$criteria->compare('order_id', $this->order_id);
        $criteria->compare('created', $this->created);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}