<?php

/**
 * This is the model base class for the table "orders".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Orders".
 *
 * Columns in table "orders" available as properties of the model,
 * followed by relations of table "orders" available as properties of the model.
 *
 * @property string $id
 * @property string $amount
 * @property string $details
 * @property string $payment_status
 * @property string $created
 * @property string $last_update
 * @property string $payer_email
 * @property string $transaction_id
 *
 * @property EnrollFormHillview[] $enrollFormHillviews
 * @property EnrollFormKnoll[] $enrollFormKnolls
 * @property EnrollFormSummer[] $enrollFormSummers
 * @property StudentSeminars[] $studentSeminars
 */
abstract class BaseOrders extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'orders';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Orders|Orders', $n);
	}

	public static function representingColumn() {
		return 'amount';
	}

	public function rules() {
		return array(
			array('amount, details, payment_status', 'required'),
			array('amount', 'length', 'max'=>10),
			array('payment_status', 'length', 'max'=>18),
			array('payer_email', 'length', 'max'=>255),
			array('transaction_id', 'length', 'max'=>45),
			array('created, last_update', 'safe'),
			array('created, last_update, payer_email, transaction_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, amount, details, payment_status, created, last_update, payer_email, transaction_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'enrollFormHillviews' => array(self::HAS_ONE, 'EnrollFormHillview', 'order_id'),
			'enrollFormKnolls' => array(self::HAS_ONE, 'EnrollFormKnoll', 'order_id'),
			'enrollFormSummers' => array(self::HAS_ONE, 'EnrollFormSummer', 'order_id'),
			'studentSeminars' => array(self::HAS_MANY, 'StudentSeminars', 'order_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'amount' => Yii::t('app', 'Amount'),
			'details' => Yii::t('app', 'Details'),
			'payment_status' => Yii::t('app', 'Payment Status'),
			'created' => Yii::t('app', 'Created'),
			'last_update' => Yii::t('app', 'Last Update'),
			'payer_email' => Yii::t('app', 'Payer Email'),
			'transaction_id' => Yii::t('app', 'Transaction'),
			'enrollFormHillviews' => null,
			'enrollFormKnolls' => null,
			'enrollFormSummers' => null,
			'studentSeminars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

        $criteria->with = ['studentSeminars'];
		$criteria->compare('id', $this->id, true);
		$criteria->compare('amount', $this->amount, true);
		$criteria->compare('details', $this->details, true);
		$criteria->compare('payment_status', $this->payment_status, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('last_update', $this->last_update, true);
		$criteria->compare('payer_email', $this->payer_email, true);
		$criteria->compare('transaction_id', $this->transaction_id, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}