<?php

/**
 * This is the model base class for the table "tutors_days_times".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TutorDayTime".
 *
 * Columns in table "tutors_days_times" available as properties of the model,
 * followed by relations of table "tutors_days_times" available as properties of the model.
 *
 * @property string $id
 * @property integer $weekday
 * @property string $start_time
 * @property string $end_time
 * @property string $tutors_id
 *
 * @property TutorStudents[] $tutorStudents
 * @property Tutors $tutors
 */
abstract class BaseTutorDayTime extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tutors_days_times';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TutorDayTime|TutorDayTimes', $n);
	}

	public static function representingColumn() {
		return 'start_time';
	}

	public function rules() {
		return array(
			array('weekday, start_time, end_time, tutors_id', 'required'),
			array('weekday', 'numerical', 'integerOnly'=>true),
			array('tutors_id', 'length', 'max'=>11),
			array('id, weekday, start_time, end_time, tutors_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tutorStudents' => array(self::HAS_MANY, 'TutorStudents', 'tutors_days_times_id'),
			'tutors' => array(self::BELONGS_TO, 'Tutors', 'tutors_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'weekday' => Yii::t('app', 'Weekday'),
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
			'tutors_id' => null,
			'tutorStudents' => null,
			'tutors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
//		$criteria->compare('weekday', $this->weekday);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('end_time', $this->end_time, true);
		$criteria->compare('tutors_id', $this->tutors_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}