<?php

/**
 * This is the model base class for the table "month_puzzle_participant".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MonthPuzzleParticipant".
 *
 * Columns in table "month_puzzle_participant" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $email
 * @property string $created
 *
 */
abstract class BaseMonthPuzzleParticipant extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'month_puzzle_participant';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MonthPuzzleParticipant|MonthPuzzleParticipants', $n);
	}

	public static function representingColumn() {
		return 'email';
	}

	public function rules() {
		return array(
			array('email', 'required'),
			array('email', 'length', 'max'=>255),
            array('email', 'email'),
			array('created', 'safe'),
			array('id, email, created', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'email' => Yii::t('app', 'Email'),
			'created' => Yii::t('app', 'Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('created', $this->created, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}