<?php

/**
 * This is the model base class for the table "student_seminars".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StudentSeminars".
 *
 * Columns in table "student_seminars" available as properties of the model,
 * followed by relations of table "student_seminars" available as properties of the model.
 *
 * @property string $id
 * @property string $student_id
 * @property string $seminar_id
 * @property string $grade_id
 * @property string $time_slot_id
 * @property string $date_period_id
 * @property integer $enroll_form_id
 * @property string $order_id
 *
 * @property Student $student
 * @property Seminar $seminar
 * @property Grade $grade
 * @property TimeSlot $timeSlot
 * @property DatePeriods $datePeriod
 * @property EnrollForms $enrollForm
 * @property Orders $order
 */
abstract class BaseStudentSeminars extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'student_seminars';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StudentSeminars|StudentSeminars', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('student_id, seminar_id, grade_id, enroll_form_id, order_id', 'required'),
			array('enroll_form_id', 'numerical', 'integerOnly'=>true),
			array('student_id, seminar_id, grade_id, time_slot_id, date_period_id, order_id', 'length', 'max'=>11),
			array('time_slot_id, date_period_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, student_id, seminar_id, grade_id, time_slot_id, date_period_id, enroll_form_id, order_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'student' => array(self::BELONGS_TO, 'Student', 'student_id'),
			'seminar' => array(self::BELONGS_TO, 'Seminar', 'seminar_id'),
			'grade' => array(self::BELONGS_TO, 'Grade', 'grade_id'),
			'timeSlot' => array(self::BELONGS_TO, 'TimeSlot', 'time_slot_id'),
			'datePeriod' => array(self::BELONGS_TO, 'DatePeriods', 'date_period_id'),
			'enrollForm' => array(self::BELONGS_TO, 'EnrollForms', 'enroll_form_id'),
			'order' => array(self::BELONGS_TO, 'Orders', 'order_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'student_id' => null,
			'seminar_id' => null,
			'grade_id' => null,
			'time_slot_id' => null,
			'date_period_id' => null,
			'enroll_form_id' => null,
			'order_id' => null,
			'student' => null,
			'seminar' => null,
			'grade' => null,
			'timeSlot' => null,
			'datePeriod' => null,
			'enrollForm' => null,
			'order' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('student_id', $this->student_id);
		$criteria->compare('seminar_id', $this->seminar_id);
		$criteria->compare('grade_id', $this->grade_id);
		$criteria->compare('time_slot_id', $this->time_slot_id);
		$criteria->compare('date_period_id', $this->date_period_id);
		$criteria->compare('enroll_form_id', $this->enroll_form_id);
		$criteria->compare('order_id', $this->order_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}