<?php

/**
 * This is the model base class for the table "student".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Student".
 *
 * Columns in table "student" available as properties of the model,
 * followed by relations of table "student" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $created
 *
 * @property StudentSeminars[] $studentSeminars
 */
abstract class BaseStudent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'student';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Student|Students', $n);
	}

	public static function representingColumn() {
		return 'created';
	}

	public function rules() {
		return array(
			array('created', 'required'),
			array('name', 'length', 'max'=>255),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, created', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'studentSeminars' => array(self::HAS_MANY, 'StudentSeminars', 'student_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'created' => Yii::t('app', 'Created'),
			'studentSeminars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('created', $this->created, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}