<?php

/**
 * This is the model base class for the table "date_periods".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DatePeriods".
 *
 * Columns in table "date_periods" available as properties of the model,
 * followed by relations of table "date_periods" available as properties of the model.
 *
 * @property string $id
 * @property string $start_date
 * @property string $end_date
 * @property string $description
 * @property string $seminar_id
 *
 * @property Seminar $seminar
 * @property StudentSeminars[] $studentSeminars
 */
abstract class BaseDatePeriods extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'date_periods';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DatePeriods|DatePeriods', $n);
	}

	public static function representingColumn() {
		return 'start_date';
	}

	public function rules() {
		return array(
			array('start_date, end_date, seminar_id', 'required'),
			array('description', 'length', 'max'=>255),
			array('seminar_id', 'length', 'max'=>11),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, start_date, end_date, description, seminar_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'seminar' => array(self::BELONGS_TO, 'Seminar', 'seminar_id'),
			'studentSeminars' => array(self::HAS_MANY, 'StudentSeminars', 'date_period_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'description' => Yii::t('app', 'Description'),
			'seminar_id' => null,
			'seminar' => null,
			'studentSeminars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('seminar_id', $this->seminar_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}