<?php

/**
 * This is the model base class for the table "student_seminars".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StudentSeminars".
 *
 * Columns in table "student_seminars" available as properties of the model,
 * followed by relations of table "student_seminars" available as properties of the model.
 *
 * @property string $id
 * @property string $student_id
 * @property string $seminar_id
 * @property string $grade_id
 * @property string $time_id
 * @property string $date_periods_id
 * @property string $cost
 * @property integer $enroll_form_id
 *
 * @property Payments[] $payments
 * @property Student $student
 * @property Seminar $seminar
 * @property Grade $grade
 * @property Time $time
 * @property DatePeriod $datePeriods
 * @property EnrollForms $enrollForm
 */
abstract class BaseStudentSeminars extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'student_seminars';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StudentSeminars|StudentSeminars', $n);
	}

	public static function representingColumn() {
		return 'cost';
	}

	public function rules() {
		return array(
			array('student_id, seminar_id, grade_id, time_id, date_periods_id, enroll_form_id', 'required'),
			array('enroll_form_id', 'numerical', 'integerOnly'=>true),
			array('student_id, seminar_id, grade_id, time_id, date_periods_id', 'length', 'max'=>11),
			array('cost', 'length', 'max'=>10),
			array('cost', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, student_id, seminar_id, grade_id, time_id, date_periods_id, cost, enroll_form_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'payments' => array(self::HAS_MANY, 'Payments', 'user_seminar_id'),
			'student' => array(self::BELONGS_TO, 'Student', 'student_id'),
			'seminar' => array(self::BELONGS_TO, 'Seminar', 'seminar_id'),
			'grade' => array(self::BELONGS_TO, 'Grade', 'grade_id'),
			'time' => array(self::BELONGS_TO, 'Time', 'time_id'),
			'datePeriods' => array(self::BELONGS_TO, 'DatePeriod', 'date_periods_id'),
			'enrollForm' => array(self::BELONGS_TO, 'EnrollForms', 'enroll_form_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'student_id' => null,
			'seminar_id' => null,
			'grade_id' => null,
			'time_id' => null,
			'date_periods_id' => null,
			'cost' => Yii::t('app', 'Cost'),
			'enroll_form_id' => null,
			'payments' => null,
			'student' => null,
			'seminar' => null,
			'grade' => null,
			'time' => null,
			'datePeriods' => null,
			'enrollForm' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('student_id', $this->student_id);
		$criteria->compare('seminar_id', $this->seminar_id);
		$criteria->compare('grade_id', $this->grade_id);
		$criteria->compare('time_id', $this->time_id);
		$criteria->compare('date_periods_id', $this->date_periods_id);
		$criteria->compare('cost', $this->cost, true);
		$criteria->compare('enroll_form_id', $this->enroll_form_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}