<?php

/**
 * This is the model base class for the table "time".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Time".
 *
 * Columns in table "time" available as properties of the model,
 * followed by relations of table "time" available as properties of the model.
 *
 * @property string $id
 * @property string $start_time
 * @property string $end_time
 * @property string $weekday
 * @property string $seminar_id
 *
 * @property StudentSeminars[] $studentSeminars
 * @property Seminar $seminar
 */
abstract class BaseTime extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'time';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Time|Times', $n);
	}

	public static function representingColumn() {
		return 'start_time';
	}

	public function rules() {
		return array(
			array('seminar_id', 'required'),
			array('weekday', 'length', 'max'=>45),
			array('seminar_id', 'length', 'max'=>11),
			array('start_time, end_time', 'safe'),
			array('start_time, end_time, weekday', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, start_time, end_time, weekday, seminar_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'studentSeminars' => array(self::HAS_MANY, 'StudentSeminars', 'time_id'),
			'seminar' => array(self::BELONGS_TO, 'Seminar', 'seminar_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
			'weekday' => Yii::t('app', 'Weekday'),
			'seminar_id' => null,
			'studentSeminars' => null,
			'seminar' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('end_time', $this->end_time, true);
		$criteria->compare('weekday', $this->weekday, true);
		$criteria->compare('seminar_id', $this->seminar_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}