<?php

/**
 * This is the model base class for the table "tutor_students".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TutorStudent".
 *
 * Columns in table "tutor_students" available as properties of the model,
 * followed by relations of table "tutor_students" available as properties of the model.
 *
 * @property integer $id
 * @property string $first_name
 * @property string $second_name
 * @property string $phone
 * @property string $email
 * @property string $alternative_time
 * @property string $other_requests
 * @property string $tutors_days_times_id
 * @property string $tutors_id
 *
 * @property TutorsDaysTimes $tutorsDaysTimes
 * @property Tutors $tutors
 */
abstract class BaseTutorStudent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tutor_students';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TutorStudent|TutorStudents', $n);
	}

	public static function representingColumn() {
		return 'first_name';
	}

	public function rules() {
		return array(
			array('first_name, second_name, phone, email, tutors_days_times_id, tutors_id', 'required'),
			array('id', 'numerical', 'integerOnly'=>true),
			array('first_name, second_name, phone, email, alternative_time', 'length', 'max'=>255),
			array('tutors_days_times_id, tutors_id', 'length', 'max'=>11),
            array('email', 'email'),
			array('other_requests', 'safe'),
			array('alternative_time, other_requests', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, first_name, second_name, phone, email, alternative_time, other_requests, tutors_days_times_id, tutors_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tutorsDaysTimes' => array(self::BELONGS_TO, 'TutorsDaysTimes', 'tutors_days_times_id'),
			'tutors' => array(self::BELONGS_TO, 'Tutors', 'tutors_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'first_name' => Yii::t('app', 'First Name'),
			'second_name' => Yii::t('app', 'Second Name'),
			'phone' => Yii::t('app', 'Phone'),
			'email' => Yii::t('app', 'Email'),
			'alternative_time' => Yii::t('app', 'Alternative Time'),
			'other_requests' => Yii::t('app', 'Other Requests'),
			'tutors_days_times_id' => null,
			'tutors_id' => null,
			'tutorsDaysTimes' => null,
			'tutors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('second_name', $this->second_name, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('alternative_time', $this->alternative_time, true);
		$criteria->compare('other_requests', $this->other_requests, true);
		$criteria->compare('tutors_days_times_id', $this->tutors_days_times_id);
		$criteria->compare('tutors_id', $this->tutors_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}